/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 15899 $ of $
 *
 * $Id:$
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef SESSIONTABLE_INTERFACE_H
#define SESSIONTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "sessionTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _sessionTable_initialize_interface(sessionTable_registration * user_ctx,
                                    u_long flags);
void _sessionTable_shutdown_interface(sessionTable_registration * user_ctx);

sessionTable_registration *
sessionTable_registration_get( void );

sessionTable_registration *
sessionTable_registration_set( sessionTable_registration * newreg );

netsnmp_container *sessionTable_container_get( void );
int sessionTable_container_size( void );

    sessionTable_rowreq_ctx * sessionTable_allocate_rowreq_ctx(sessionTable_data *, void *);
void sessionTable_release_rowreq_ctx(sessionTable_rowreq_ctx *rowreq_ctx);

int sessionTable_index_to_oid(netsnmp_index *oid_idx,
                            sessionTable_mib_index *mib_idx);
int sessionTable_index_from_oid(netsnmp_index *oid_idx,
                              sessionTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void sessionTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* SESSIONTABLE_INTERFACE_H */
/** @} */
