/*
 * Note: this file originally auto-generated by mib2c using
 *  : generic-table-enums.m2c 12526 2005-07-15 22:41:16Z rstory $
 *
 * $Id:$
 */
#ifndef SESSIONTABLE_ENUMS_H
#define SESSIONTABLE_ENUMS_H

#ifdef __cplusplus
extern "C" {
#endif

 /*
 * NOTES on enums
 * ==============
 *
 * Value Mapping
 * -------------
 * If the values for your data type don't exactly match the
 * possible values defined by the mib, you should map them
 * below. For example, a boolean flag (1/0) is usually represented
 * as a TruthValue in a MIB, which maps to the values (1/2).
 *
 */
/*************************************************************************
 *************************************************************************
 *
 * enum definitions for table sessionTable
 *
 *************************************************************************
 *************************************************************************/

/*************************************************************
 * constants for enums for the MIB node
 * sesType (IANAtunnelType / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef IANATUNNELTYPE_ENUMS
#define IANATUNNELTYPE_ENUMS

#define IANATUNNELTYPE_OTHER  1
#define IANATUNNELTYPE_DIRECT  2
#define IANATUNNELTYPE_GRE  3
#define IANATUNNELTYPE_MINIMAL  4
#define IANATUNNELTYPE_L2TP  5
#define IANATUNNELTYPE_PPTP  6
#define IANATUNNELTYPE_L2F  7
#define IANATUNNELTYPE_UDP  8
#define IANATUNNELTYPE_ATMP  9
#define IANATUNNELTYPE_MSDP  10
#define IANATUNNELTYPE_SIXTOFOUR  11
#define IANATUNNELTYPE_SIXOVERFOUR  12
#define IANATUNNELTYPE_ISATAP  13
#define IANATUNNELTYPE_TEREDO  14

#endif /* IANATUNNELTYPE_ENUMS */


/*************************************************************
 * constants for enums for the MIB node
 * sesState (INTEGER / ASN_INTEGER)
 *
 * since a Textual Convention may be referenced more than once in a
 * MIB, protect againt redefinitions of the enum values.
 */
#ifndef SESSTATE_ENUMS
#define SESSTATE_ENUMS

#define SESSTATE_STARTING  1
#define SESSTATE_ACTIVE  2
#define SESSTATE_FINISHING  3

#endif /* SESSTATE_ENUMS */




#ifdef __cplusplus
}
#endif

#endif /* SESSIONTABLE_ENUMS_H */
