/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf 13957 2005-12-20 15:33:08Z tanders $
 */
#ifndef STATSSTP_H
#define STATSSTP_H

/* function declarations */
void init_statSSTP(void);

#endif /* STATSSTP_H */
