/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef STATCORE_H
#define STATCORE_H

/* function declarations */
void init_statCore(void);
Netsnmp_Node_Handler handle_statCoreUpTime;
Netsnmp_Node_Handler handle_statCoreCPU;
Netsnmp_Node_Handler handle_statCoreMemRss;

#endif /* STATCORE_H */
