/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf 13957 2005-12-20 15:33:08Z tanders $
 */
#ifndef STATPPPOE_H
#define STATPPPOE_H

/* function declarations */
void init_statPPPOE(void);

#endif /* STATPPPOE_H */
