/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf 13957 2005-12-20 15:33:08Z tanders $
 */
#ifndef STATIPOE_H
#define STATIPOE_H

/* function declarations */
void init_statIPOE(void);

#endif /* STATPPPOE_H */
