/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf 13957 2005-12-20 15:33:08Z tanders $
 */
#ifndef STATPPTP_H
#define STATPPTP_H

/* function declarations */
void init_statPPTP(void);

#endif /* STATPPTP_H */
