/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf 13957 2005-12-20 15:33:08Z tanders $
 */
#ifndef STATL2TP_H
#define STATL2TP_H

/* function declarations */
void init_statL2TP(void);

#endif /* STATL2TP_H */
