/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef TERMINATE_H
#define TERMINATE_H

/* function declarations */
void init_terminate(void);
Netsnmp_Node_Handler handle_termBySID;
Netsnmp_Node_Handler handle_termByIfName;
Netsnmp_Node_Handler handle_termByIP;
Netsnmp_Node_Handler handle_termByUsername;

#endif /* TERMINATE_H */
