SET(CPACK_PACKAGING_INSTALL_PREFIX "/")
SET(CPACK_DEBIAN_PACKAGE_ARCHITECTURE ${ARCH})

if (BUILD_DRIVER_ONLY)
	SET(CPACK_PACKAGE_NAME "accel-pptp-kmod")
	SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "accel-pptp kernel module")
	SET(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${CMAKE_CURRENT_SOURCE_DIR}/cmake/debian-kmod/postinst")
	INSTALL(FILES ${CMAKE_CURRENT_BINARY_DIR}/driver/driver/pptp.ko DESTINATION lib/modules/${DEBIAN_KDIR}/extra)
	#SET(CPACK_DEBIAN_PACKAGE_DEPENDS "linux-image (= ${LINUX_IMAGE})")
else (BUILD_DRIVER_ONLY)	
	SET(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.7), libssl0.9.8 (>= 0.9.8)")
	SET(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${CMAKE_CURRENT_SOURCE_DIR}/cmake/debian/preinst;${CMAKE_CURRENT_SOURCE_DIR}/cmake/debian/postinst")

	INSTALL(FILES ${CMAKE_HOME_DIRECTORY}/contrib/debian/accel-pptp-init DESTINATION etc/init.d RENAME accel-pptp)
	INSTALL(FILES ${CMAKE_HOME_DIRECTORY}/contrib/debian/accel-pptp-default DESTINATION etc/default RENAME accel-pptp)
endif (BUILD_DRIVER_ONLY)

