SET(CPACK_DEBIAN_PACKAGE_ARCHITECTURE $ARCH)
SET(CPACK_DEBIAN_PACKAGE_DEPENDS libc6 libssl)
SET(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${CMAKE_CURRENT_SOURCE_DIR}/cmake/debian/postinst;${CMAKE_CURRENT_SOURCE_DIR}/cmake/debian/preinst")


